### ISSUE TITLE
Parent access into child iframe

### ISSUE THREAD

**Issue by jdalton** [dtapuska/documentaccess#3]
Would document-access that restricts the child from reaching into the parent prevent the parent from reaching into the child iframe? I’m looking for a way for the parent to access the child but restrict the child from accessing the parent.

**Comment by dtapuska** [comment]
No it doesn't do that. Access is restricted both ways  You can still use postMessage either way though. Does that not work for you?

**Comment by jdalton** [comment]
> Does that not work for you?

Unfortunately not. Here's what/how I'm trying to accomplish:
Dynamically create an iframe with `document.createElement()`, set some `sandbox` restrictions, set its `src` via a `new Blob()` and `URL.createObjectURL()`. * Pseudo time * - the iframe has code injected in the blob to run first and grab references to the parent and cut ties (ideally). So then I could have a synchronous route into the iframe without the iframe being able to walk back up the parent and compromise the parent.

For sandboxing content async isn't always preferred. See [this post](https://www.figma.com/blog/how-we-built-the-figma-plugin-system/) as an example of when async becomes unwieldy. We're facing this same problem at Salesforce and have had to create very complex virtual realms to try and deal with the lack of synchronous functionality in a sandbox.

**Comment by jdalton** [comment]
It looks like the real problem is with the `window.top` which is immutable. If there was a way to disable access to `window.top` even for same-origin iframes, while keeping mutable access to `parent` and `frameElement`, then my scenario would be fulfilled.

**Comment by dtapuska** [comment]
Even if you could get a handled to it something could collude to pass you a handle or assign a variable in your frame. You want to do this at the security layer. And the current proposal is to segregate them entirely in different agent clusters. That means a bidirectional separation. Sorry but this proposal won't help your situation.

**Comment by jdalton** [comment]
Can you provide an example of how, if I create the iframe with source that grabs a reference to the `parent` and then overwrite the `parent` and `frameElement` with `Reflect.defineProperty` to be `null`, another script added could corrupt or collude to muck with it?

**Comment by dtapuska** [comment]
There are a few examples. Say before I parent gets nulled out, I add an event listener in my parent and that incumbent realm will now be the parents, so then I'll have a reference to the parent window when that event listener runs.

A sibling iframe could easy reach into "restricted" iframe and set an arbitrary value that is just a reference to the parent.

I'm sure there are other ways.  How are you going to post messages to your parent? Do you not need to be able to do that?

**Comment by jdalton** [comment]
> Say before I parent gets nulled out, I add an event listener in my parent and that incumbent realm will now be the parents, so then I'll have a reference to the parent window when that event listener runs.

Ok, so far no issue.

> A sibling iframe could easy reach into "restricted" iframe and set an arbitrary value that is just a reference to the parent.

Sibling iframes are restricted in the same way so they have no way to reach out of their frame from third-party code.

> How are you going to post messages to your parent? Do you not need to be able to do that?

With direct parent access via the `parent` reference which is then removed for third-party access I can communicate in a synchronous way to the parent without needing to rely on `postMessage`.

**Comment by jdalton** [comment]
After working on things a bit I'm wondering if a more palatable change would be to allow creating an iframe whose `window.top` is `null` or opaque (even if it's treated as of the same origin) from the start. Maybe this could shake out of more granular document-access rules.
